# Generated by Django 3.2.7 on 2021-09-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritepublication',
            name='news',
        ),
        migrations.RemoveField(
            model_name='law',
            name='favourite_laws',
        ),
        migrations.AddField(
            model_name='favouritepublication',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.news'),
        ),
        migrations.AddField(
            model_name='law',
            name='type',
            field=models.IntegerField(choices=[(1, 'Действующее законодательство'), (2, 'Проеткы')], null=True, verbose_name=((1, 'Действующее законодательство'), (2, 'Проеткы'))),
        ),
    ]
